name = "cpd-backend-express"
main = "worker.js"  # Point this to your entry file
compatibility_date = "2024-11-01"
compatibility_flags = [ "nodejs_compat" ]

# This tells Cloudflare to bundle your node_modules
[build]
command = "npm install" # If you have a build step, otherwise just remove